"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[cmd_duration]
disabled = true

[git_status]
renamed = "r"

[aws]
symbol = "aws "

[azure]
symbol = "az "

[buf]
symbol = "buf "
format = "via [$symbol]($style)"

[bun]
symbol = "bun "
format = "via [$symbol]($style)"

[c]
symbol = "C "

[cobol]
symbol = "cobol "
format = "via [$symbol]($style)"

[conda]
symbol = "conda "

[crystal]
symbol = "cr "
format = "via [$symbol]($style)"

[cmake]
symbol = "cmake "
format = "via [$symbol]($style)"

[daml]
symbol = "daml "
format = "via [$symbol]($style)"

[dart]
symbol = "dart "
format = "via [$symbol]($style)"

[deno]
symbol = "deno "
format = "via [$symbol]($style)"

[dotnet]
symbol = ".NET "
format = "[$symbol(🎯 $tfm )]($style)"

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "
format = 'via [$symbol]($style)'

[elm]
symbol = "elm "
format = 'via [$symbol]($style)'

[fennel]
symbol = "fnl "
format = 'via [$symbol]($style)'

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[gleam]
symbol = "gleam "
format = 'via [$symbol]($style)'

[golang]
symbol = "go "
format = 'via [$symbol]($style)'

[gradle]
symbol = "gradle "
format = 'via [$symbol]($style)'

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "
format = 'via [$symbol]($style)'

[julia]
symbol = "jl "
format = 'via [$symbol]($style)'

[kotlin]
symbol = "kt "
format = 'via [$symbol]($style)'

[lua]
symbol = "lua "
format = 'via [$symbol]($style)'

[nodejs]
symbol = "nodejs "
format = 'via [$symbol]($style)'

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "
format = 'via [$symbol]($style)'

[nats]
symbol = "nats "

[nim]
symbol = "nim "
format = 'via [$symbol]($style)'

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
symbol = "opa "
format = 'via [$symbol]($style)'

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "
format = 'via [$symbol]($style)'

[php]
symbol = "php "
format = 'via [$symbol]($style)'

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "
format = 'via [$symbol$stack]($style)'

[purescript]
symbol = "purs "
format = 'via [$symbol]($style)'

[python]
symbol = "py "
format = 'via [$symbol]($style)'

[quarto]
symbol = "quarto "
format = 'via [$symbol]($style)'

[raku]
symbol = "raku "
format = 'via [$symbol]($style)'

[ruby]
symbol = "rb "
format = 'via [$symbol]($style)'

[rust]
symbol = "rs "
format = 'via [$symbol]($style)'

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "
format = 'via [$symbol]($style)'

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
format = 'via [$symbol]($style)'

[typst]
symbol = "typst "
format = 'via [$symbol]($style)'

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
format = 'via [$symbol]($style)'

[erlang]
format = 'via [$symbol]($style)'

[haxe]
format = 'via [$symbol]($style)'

[helm]
format = 'via [$symbol]($style)'


[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'
